version: "3.2"
services:
  web:
    image: "registry.thinklabs.com.vn:5000/tcameratrafficdevweb:latest"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.environment==development]
      restart_policy:
        condition: any
    environment:
      PORT: 80
      NODE_ENV: "production"
      SERVICE_80_NAME: "tcameratrafficdevweb"
      SERVICE_NAME: "tcameratrafficdevweb"
      SERVICE_TAGS: "tcameratrafficdevweb"
    # networks:
    #   - host
    ports:
      - target: 80
        published: 8100
        mode: host

# networks:
#   host:
